---
title: "validate_metadata_quality"
format: html
editor: visual
---

### Packages

```{r}
library(readxl)
library(dplyr)
library(tidyverse)
library(janitor)
```

### Read in Pre-Human Verified File

```{r}
df <- read.csv("/home/nshanbha/KIDS26-Team11/scripts/data_ingestion/combined_metadata.csv")

df <- df %>% mutate(SRM_concat = paste(srm_order_number,srm_sample_number, sep = "-")) %>% relocate(SRM_concat, .after = srm_sample_number)
```

### Pre Summary File

```{r}
summary_stats <- function(column, df) {
  unique <- df %>% distinct(.data[[column]]) %>% nrow()
  dupes <- df %>% filter(!is.na(.data[[column]])) %>% count(.data[[column]]) %>% filter(n > 1) %>% summarize(dupes = sum(n - 1))  %>% pull()
  missing <- df %>% filter(is.na(.data[[column]])) %>% nrow() 
  c(column = column, unique = unique, dupes = dupes, missing = missing)
}

column_names <- c("lab_id_number", "sample_name", "srm_order_number", "srm_sample_number")

summary_df <- map_dfr(column_names, summary_stats, df = df) %>% mutate(across(-column, as.numeric))

plot <- summary_df %>% pivot_longer(cols = -column, names_to = "category", values_to = "value") %>% ggplot(aes(x = column, y = value, fill = category)) + geom_col(position = "dodge") + xlab("Category") + ylab("Number of Entries") + ggtitle("Distribution of Data") + geom_text(
    aes(label = value),
    position = position_dodge(width = 0.9),
    vjust = -0.3
  ) +  theme_classic()


ggsave("/home/nshanbha/KIDS26-Team11/scripts/human_reviewers/pre-human/data_breakdown.png", plot, width = 15, height = 12)

```

### Check Exceptions (Pre)

```{r}
#1 Duplicate SRM Sample # but DYE different (must flag this, it's an error) - if it's multiplex or 10x barcode, then it is okay
duplicate_SRM_samples <- df %>% group_by(srm_sample_number) %>% filter(n() > 1) %>% filter(!str_detect(assay, regex("multiplex|powerplex|10x", ignore_case = TRUE)))

#2 Duplicate DYE but the SRM different (resequenced) - the SRM order and SRM sample act as a unique identifier. If the SRM order and SRM sample are the same, then flag it. In this case, eliminate embryoid bodies
duplicate_DYE <- df %>% group_by(lab_id_number) %>% filter(n() > 1) %>% group_by(lab_id_number, SRM_concat) %>% filter(n() > 1)

#3 Missing SRM Lab ID
missing_lab_id <- df %>% filter(is.na(lab_id_number))

#4 Missing SRM Order # - 
missing_SRM_order <- df %>% filter(is.na(srm_order_number))

#5 Missing SRM Sample # - 
missing_SRM_sample <- df %>% filter(is.na(srm_sample_number))

#6 Missing SRM Sample Name -
missing_sample_names <- df %>% filter(is.na(sample_name))

#7 Lab ID fall out of DYE, DY, or SJNorm
weird_lab_id <- df %>% filter(!str_detect(pattern = "DYE|DY|SJMMNOR|MDSEQ", lab_id_number))

write.csv(missing_lab_id,"/home/nshanbha/KIDS26-Team11/scripts/human_reviewers/pre-human/missing_lab_ids.csv")
write.csv(duplicate_SRM_samples, "/home/nshanbha/KIDS26-Team11/scripts/human_reviewers/pre-human/duplicate_SRM_samples.csv")
write.csv(duplicate_DYE, "/home/nshanbha/KIDS26-Team11/scripts/human_reviewers/pre-human/duplicate_DYE.csv")
write.csv(missing_SRM_order, "/home/nshanbha/KIDS26-Team11/scripts/human_reviewers/pre-human/missing_SRM_order.csv")
write.csv(missing_SRM_sample, "/home/nshanbha/KIDS26-Team11/scripts/human_reviewers/pre-human/missing_SRM_samples.csv")
write.csv(missing_sample_names, "/home/nshanbha/KIDS26-Team11/scripts/human_reviewers/pre-human/missing_sample_names.csv")
write.csv(weird_lab_id, "/home/nshanbha/KIDS26-Team11/scripts/human_reviewers/pre-human/weird_lab_id.csv")

cols <- c("duplicate_SRM_samples", "duplicate_DYE", "missing_lab_id", "missing_SRM_order", "missing_SRM_sample", "missing_sample_names", "weird_lab_id")
values <- c(duplicate_SRM_samples %>% nrow(), duplicate_DYE %>% nrow(), missing_lab_id %>% nrow(), missing_SRM_order %>% nrow(), missing_SRM_sample %>% nrow(), missing_sample_names %>% nrow(), weird_lab_id %>% nrow())

exception_breakdown <- data.frame(t(values)) |> setNames(cols) %>% pivot_longer(cols = everything(), names_to = "category", values_to = "value") 

plot <- exception_breakdown %>% ggplot(aes(x = category, y = value)) +   geom_col(position = "dodge") +
  geom_text(
    aes(label = value),
    position = position_dodge(width = 0.9),
    vjust = 0.5, hjust = -0.5
  ) +
  labs(
    x = "Category",
    y = "Number of Entries",
    title = "Distribution of Data Pre Human Validation"
  ) +
  theme_classic() +
  coord_flip() 

ggsave("/home/nshanbha/KIDS26-Team11/scripts/human_reviewers/pre-human/exception_breakdown.png", plot, width = 15, height = 12)

```

### Read in Human Verified File

```{r}
df_MA <- read.csv("/home/nshanbha/KIDS26-Team11/scripts/data_ingestion/combined_metadata_MA.csv")

df_MA <- df_MA %>% mutate(SRM_concat = paste(srm_order_number,srm_sample_number, sep = "-")) %>% relocate(SRM_concat, .after = srm_sample_number)
```

### Post Summary File

```{r}
summary_stats <- function(column, df) {
  unique <- df %>% distinct(.data[[column]]) %>% nrow()
  dupes <- df %>% filter(!is.na(.data[[column]])) %>% count(.data[[column]]) %>% filter(n > 1) %>% summarize(dupes = sum(n - 1))  %>% pull()
  missing <- df %>% filter(is.na(.data[[column]])) %>% nrow() 
  c(column = column, unique = unique, dupes = dupes, missing = missing)
}

column_names <- c("lab_id_number", "sample_name", "srm_order_number", "srm_sample_number")

summary_df <- map_dfr(column_names, summary_stats, df = df_MA) %>% mutate(across(-column, as.numeric))

plot <- summary_df %>% pivot_longer(cols = -column, names_to = "category", values_to = "value") %>% ggplot(aes(x = column, y = value, fill = category)) + geom_col(position = "dodge") + xlab("Category") + ylab("Number of Entries") + ggtitle("Distribution of Data") + geom_text(
    aes(label = value),
    position = position_dodge(width = 0.9),
    vjust = -0.3
  ) +  theme_classic()

ggsave("/home/nshanbha/KIDS26-Team11/scripts/human_reviewers/post-human/data_breakdown.png", plot, width = 15, height = 12)
```

### Check Exceptions (Post)

```{r}
#1 Duplicate SRM Sample # but DYE different (must flag this, it's an error) - if it's multiplex or 10x barcode, then it is okay
duplicate_SRM_samples <- df_MA %>% group_by(srm_sample_number) %>% filter(n() > 1) %>% filter(!str_detect(assay, regex("multiplex|powerplex|10x", ignore_case = TRUE)))

#2 Duplicate DYE but the SRM different (resequenced) - the SRM order and SRM sample act as a unique identifier. If the SRM order and SRM sample are the same, then flag it. In this case, eliminate embryoid bodies
duplicate_DYE <- df_MA %>% group_by(lab_id_number) %>% filter(n() > 1) %>% group_by(lab_id_number, SRM_concat) %>% filter(n() > 1)

#3 Missing SRM Lab ID
missing_lab_id <- df_MA %>% filter(is.na(lab_id_number))

#4 Missing SRM Order # - 
missing_SRM_order <- df_MA %>% filter(is.na(srm_order_number))

#5 Missing SRM Sample # - 
missing_SRM_sample <- df_MA %>% filter(is.na(srm_sample_number))

#6 Missing SRM Sample Name -
missing_sample_names <- df_MA %>% filter(is.na(sample_name))

#7 Lab ID fall out of DYE, DY, or SJNorm
weird_lab_id <- df_MA %>% filter(!str_detect(pattern = "DYE|DY|SJMMNOR|MDSEQ", lab_id_number))


write.csv(duplicate_SRM_samples, "/home/nshanbha/KIDS26-Team11/scripts/human_reviewers/post-human/duplicate_SRM_samples.csv")
write.csv(duplicate_DYE, "/home/nshanbha/KIDS26-Team11/scripts/human_reviewers/post-human/duplicate_DYE.csv")
write.csv(missing_lab_id,"/home/nshanbha/KIDS26-Team11/scripts/human_reviewers/post-human/missing_lab_ids.csv" )
write.csv(missing_SRM_order, "/home/nshanbha/KIDS26-Team11/scripts/human_reviewers/post-human/missing_SRM_order.csv")
write.csv(missing_SRM_sample, "/home/nshanbha/KIDS26-Team11/scripts/human_reviewers/post-human/missing_SRM_samples.csv")
write.csv(missing_sample_names, "/home/nshanbha/KIDS26-Team11/scripts/human_reviewers/post-human/missing_sample_names.csv")
write.csv(weird_lab_id, "/home/nshanbha/KIDS26-Team11/scripts/human_reviewers/post-human/weird_lab_id.csv")

cols <- c("duplicate_SRM_samples", "duplicate_DYE", "missing_lab_id", "missing_SRM_order", "missing_SRM_sample", "missing_sample_names", "weird_lab_id")
values <- c(duplicate_SRM_samples %>% nrow(), duplicate_DYE %>% nrow(), missing_lab_id %>% nrow(), missing_SRM_order %>% nrow(), missing_SRM_sample %>% nrow(), missing_sample_names %>% nrow(), weird_lab_id %>% nrow())

exception_breakdown <- data.frame(t(values)) |> setNames(cols) %>% pivot_longer(cols = everything(),
                                                         names_to = "category",
                                                         values_to = "value")

plot <- exception_breakdown %>% ggplot(aes(x = category, y = value)) + geom_col(position = "dodge") +
  geom_text(
    aes(label = value),
    position = position_dodge(width = 0.9),
    vjust = -0.5,
    hjust = -0.5
  ) +
  labs(x = "Category", y = "Number of Entries", title = "Distribution of Data Post-Human Validation") +
  theme_classic() +
  coord_flip()

ggsave("/home/nshanbha/KIDS26-Team11/scripts/human_reviewers/post-human/exception_breakdown.png", plot, width = 15, height = 12)
```
